### ISSUE TITLE
Code review.

### ISSUE THREAD

**Issue by kgryte** [compute-io/ones#1]
Addresses compute-io/todo#111.

**Comment by Planeshifter** [comment]
See my comment on compute-io/zeros#2. Looks good to me otherwise, voting for release.

**Comment by kgryte** [comment]
Fixed the output data type description and replied to your comment. Thanks for reviewing!

**Comment by kgryte** [comment]
@Planeshifter: split things into separate files. Probably worth taking another look. Thanks!

**Comment by Planeshifter** [comment]
Package landed on npm.

**Comment by kgryte** [comment]
Awesome. Thanks!
