### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by kgryte** [compute-io/ones#2]
This module still uses `coveralls` as a dependency rather than `codecov`. Will need to `patch`.

**Comment by Planeshifter** [comment]
Thanks! Will do so now. I have `codecov` installed as a global dependency and thus was still able to run all tests locally. Hopefully the travis-io bug is resolved soon, which would have prevented this oversight of my part.

**Comment by kgryte** [comment]
Yeah. The NPM bug should never have happened and should have been resolved immediately, as people's builds break, which is never a good thing to do.

**Comment by Planeshifter** [comment]
Patch landed. Thanks again for catching this!

**Comment by kgryte** [comment]
No prob. Thanks for the patch and updates!
